Repository ckdwlsrh/team_3_project, pull requests merged in 2025-03, with the labels that each got.

#6 Add payment page, 결제 페이지 추가
  payment.html
Labels: enhancement

#11 docs: 메인 리드미 수정
  README.md
Labels: documentation

#9 Move Files
  css/payment.css
  js/payment.js
  pages/payment.html
Labels: documentation

#12 feature: 장바구니 만들기
  css/cart.css
  js/cart.js
  pages/cart.html
Labels: good first issue

#13 feat: 메인페이지에 상품페이지 바로가기 작성
  index.html
Labels: enhancement
